// Regenerated. Newest first.
window.RECORDINGS = [
  {
    "id": "recording-1-paris-test",
    "title": "Mystery Shopper Job Inquiry — Parisian Native (TEST)",
    "date": "2026-06-24",
    "source": "s2t-test",
    "french": [
      "Bonjour. Euh, alors je viens de voir votre annonce en ligne sur, euh, genre, le fait de devenir client mystère pour vous. Euh, donc je voulais, enfin je voulais juste vous appeler parce que j'avais deux-trois questions quand j'ai vu l'annonce, si ça vous dérange pas. Super.",
      "Euh, alors déjà, euh, je vois pas trop ce que c'est, les missions. Du coup c'est, c'est quoi exactement, une mission ? Genre, euh, je, je sais qu'on va, euh, qu'on va aller faire des courses, qu'on va aller au restaurant, tout ça. En gros on va acheter les services des autres, quoi. Euh, mais du coup après, qu'est-ce qui se passe ?",
      "D'accord. Euh, et j'imagine que ma question c'est plutôt, genre, qu'est-ce que vous allez faire de cette évaluation ? Genre, euh, vous allez la poster en ligne ? Vous euh— est-ce que, est-ce que notre nom est associé à ça quand vous le postez en ligne ? Si c'est le cas, ben c'est ça la partie que je voudrais clarifier. D'accord. Euh, et est-ce que les— enfin, est-ce que les évaluations, euh, sont postées en ligne, ou alors c'est juste pour votre, j'imagine, euh, pour, pour votre base de connaissances interne, pour connaître vos concurrents ou je sais pas quoi ? D'accord. D'accord. Je vois.",
      "Euh, et je voulais aussi en savoir plus sur la rémunération. Euh, donc vous avez dit que la paye dépend des missions. Euh, vous pourriez développer un peu ? Je vois. D'accord.",
      "Euh, et on peut espérer avoir combien de missions, genre, par mois ? Parce que, euh, je, je me demande s'il y aura une forme de régularité à l'avenir une fois qu'on aura un peu d'expérience, parce que je sais que, genre, quand on débute, ben les missions arrivent peut-être pas de manière régulière, mais je me demande si ça pourrait finir par atteindre le point où, genre, on a des missions genre régulièr— de manière régulière, du coup c'est plus prévisible. D'accord. Je vois.",
      "Et euh, j'imagine, euh, pour, pour un livreur expérimenté, euh, ça, ça représenterait quoi comme chiffre ? Combien de missions ils auraient par mois et ça ferait combien au total, la paie sur toutes les missions ? D'accord. D'accord. Je vois.",
      "Euh, et est-ce que, est-ce qu'il y a un peu des, genre des primes, j'imagine, en plus de ça ? Je vois. D'accord.",
      "Euh, et au niveau des disponibilités, euh, quand est-ce que vous attendez normalement de nous qu'on prenne des missions ? Euh, je me demande juste si je peux caser ça comme un truc à faire après mon travail, qui, qui finit en gros à dix-sept heures. Euh, du coup voilà, je, je me demande si ça collerait avec mon emploi du temps. D'accord. Je vois.",
      "Et, euh, vous savez, au niv-, euh, au niveau de dans certains cas où il y aurait genre beaucoup plus de circulation que d'habitude, euh, est-ce qu'on est dédommagé pour ce temps en plus qu'on passe sur une mission ? Hmm. D'accord. Je vois.",
      "Euh, super. Je réfléchis juste aux questions que je pourrais encore avoir. Euh, du coup, euh, la dernière question que j'avais, c'est, euh, est-ce qu'il y a quelque chose que je dois, euh, une-, une expérience que je dois avoir au préalable avant de pouvoir genre postuler, ou que-- pour que vous considériez ma candidature ? D'accord. Super. Et voilà, euh, du coup, euh, je vais postuler alors. Voilà. Merci beaucoup d'avoir répondu à mes questions."
    ],
    "english": [
      "Hi. Um, so I just saw your posting online about, um, you know, becoming a mystery shopper for you guys. Um, so I just, I just wanted to call you guys because I had a couple questions when I saw the posting, if that's okay with you. Great.",
      "Um, so first of all, um, I'm not really clear on what missions are. So what, what do you mean by missions? So, um, I, I know that, you know, we'll be, uh, we'll be going shopping, we'll be going through a restaurant, all that stuff. We'll be essentially buying other people's services. Um, but then what's next after that?",
      "Okay. Um, and I guess my question is more about like, what are you going to do with that evaluation? Like, um, are you going to post about it online? Do you like-- Is, is our name involved with that when you post it online? If that's the case, like that's the part that I want to clarify on. Okay. Um, and are the-- So are the evaluations, um, posted online or is it just for your internal, I guess, um, for, for your internal knowledge base to know about your competitors or whatever the case may be? Okay. Okay. I see.",
      "Um, and I also want to know more about the pay. Um, so you mentioned that the pay is based on missions. Um, could you elaborate on that? I see. Okay.",
      "Um, and how many missions can we expect to get, you know, like per month? Because, um, I, I'm wondering if there will be some sort of consistency in the future once we get a certain amount of experience because I know, you know, as a beginner, like the missions might not come like consistently, but I'm wondering if it could eventually reach that point where, you know, we get missions like consistent-- on a consistent basis so it's more predictable. Okay. I see.",
      "And I guess, um, for, for an experienced shopper, um, what, what would that number look like? How many missions would they get per month and what would their total pay across all the missions be? Okay. Okay. I see.",
      "Um, and is, is-- are there any sort of like bonuses, I guess on top of this? Got it. Okay.",
      "Um, and in terms of availability, um, when do you normally expect us to take on missions? Um, I'm just wondering if I can fit this in as a thing to do after my day job, which is-- which basically ends at five PM. Um, so yeah, I'm, I'm wondering if that would work with my schedule. Okay. I see.",
      "And, um, you know, in term, uh, in terms of like in, in certain cases where there may be like a lot more traffic than normal, um, do we get compensated for that extra time that we spend doing a particular mission? Mm. Okay. I see.",
      "Um, cool. I'm just thinking of what more questions I may have. Um, I guess, uh, the last question I had is, um, is there anything that I need to, um, a-any sort of experience that I need to have beforehand before I can like apply for this or be-- for you to consider my application? Okay. Cool. And yeah, I guess, uh, I'll apply then. Yeah. Thank you very much for answering my questions."
    ],
    "audio": "audio/recording-1-paris-test.mp3"
  },
  {
    "id": "recording-1-cs-surgical",
    "title": "Mystery Shopper — Parisian · audio NO filler-commas (TEST)",
    "date": "2026-06-24",
    "source": "s2t-test",
    "french": [
      "Bonjour. Euh, alors je viens de voir votre annonce en ligne sur, euh, genre, le fait de devenir client mystère pour vous. Euh, donc je voulais, enfin je voulais juste vous appeler parce que j'avais deux-trois questions quand j'ai vu l'annonce, si ça vous dérange pas. Super.",
      "Euh, alors déjà, euh, je vois pas trop ce que c'est, les missions. Du coup c'est, c'est quoi exactement, une mission ? Genre, euh, je, je sais qu'on va, euh, qu'on va aller faire des courses, qu'on va aller au restaurant, tout ça. En gros on va acheter les services des autres, quoi. Euh, mais du coup après, qu'est-ce qui se passe ?",
      "D'accord. Euh, et j'imagine que ma question c'est plutôt, genre, qu'est-ce que vous allez faire de cette évaluation ? Genre, euh, vous allez la poster en ligne ? Vous euh— est-ce que, est-ce que notre nom est associé à ça quand vous le postez en ligne ? Si c'est le cas, ben c'est ça la partie que je voudrais clarifier. D'accord. Euh, et est-ce que les— enfin, est-ce que les évaluations, euh, sont postées en ligne, ou alors c'est juste pour votre, j'imagine, euh, pour, pour votre base de connaissances interne, pour connaître vos concurrents ou je sais pas quoi ? D'accord. D'accord. Je vois.",
      "Euh, et je voulais aussi en savoir plus sur la rémunération. Euh, donc vous avez dit que la paye dépend des missions. Euh, vous pourriez développer un peu ? Je vois. D'accord.",
      "Euh, et on peut espérer avoir combien de missions, genre, par mois ? Parce que, euh, je, je me demande s'il y aura une forme de régularité à l'avenir une fois qu'on aura un peu d'expérience, parce que je sais que, genre, quand on débute, ben les missions arrivent peut-être pas de manière régulière, mais je me demande si ça pourrait finir par atteindre le point où, genre, on a des missions genre régulièr— de manière régulière, du coup c'est plus prévisible. D'accord. Je vois.",
      "Et euh, j'imagine, euh, pour, pour un livreur expérimenté, euh, ça, ça représenterait quoi comme chiffre ? Combien de missions ils auraient par mois et ça ferait combien au total, la paie sur toutes les missions ? D'accord. D'accord. Je vois.",
      "Euh, et est-ce que, est-ce qu'il y a un peu des, genre des primes, j'imagine, en plus de ça ? Je vois. D'accord.",
      "Euh, et au niveau des disponibilités, euh, quand est-ce que vous attendez normalement de nous qu'on prenne des missions ? Euh, je me demande juste si je peux caser ça comme un truc à faire après mon travail, qui, qui finit en gros à dix-sept heures. Euh, du coup voilà, je, je me demande si ça collerait avec mon emploi du temps. D'accord. Je vois.",
      "Et, euh, vous savez, au niv-, euh, au niveau de dans certains cas où il y aurait genre beaucoup plus de circulation que d'habitude, euh, est-ce qu'on est dédommagé pour ce temps en plus qu'on passe sur une mission ? Hmm. D'accord. Je vois.",
      "Euh, super. Je réfléchis juste aux questions que je pourrais encore avoir. Euh, du coup, euh, la dernière question que j'avais, c'est, euh, est-ce qu'il y a quelque chose que je dois, euh, une-, une expérience que je dois avoir au préalable avant de pouvoir genre postuler, ou que-- pour que vous considériez ma candidature ? D'accord. Super. Et voilà, euh, du coup, euh, je vais postuler alors. Voilà. Merci beaucoup d'avoir répondu à mes questions."
    ],
    "english": [
      "Hi. Um, so I just saw your posting online about, um, you know, becoming a mystery shopper for you guys. Um, so I just, I just wanted to call you guys because I had a couple questions when I saw the posting, if that's okay with you. Great.",
      "Um, so first of all, um, I'm not really clear on what missions are. So what, what do you mean by missions? So, um, I, I know that, you know, we'll be, uh, we'll be going shopping, we'll be going through a restaurant, all that stuff. We'll be essentially buying other people's services. Um, but then what's next after that?",
      "Okay. Um, and I guess my question is more about like, what are you going to do with that evaluation? Like, um, are you going to post about it online? Do you like-- Is, is our name involved with that when you post it online? If that's the case, like that's the part that I want to clarify on. Okay. Um, and are the-- So are the evaluations, um, posted online or is it just for your internal, I guess, um, for, for your internal knowledge base to know about your competitors or whatever the case may be? Okay. Okay. I see.",
      "Um, and I also want to know more about the pay. Um, so you mentioned that the pay is based on missions. Um, could you elaborate on that? I see. Okay.",
      "Um, and how many missions can we expect to get, you know, like per month? Because, um, I, I'm wondering if there will be some sort of consistency in the future once we get a certain amount of experience because I know, you know, as a beginner, like the missions might not come like consistently, but I'm wondering if it could eventually reach that point where, you know, we get missions like consistent-- on a consistent basis so it's more predictable. Okay. I see.",
      "And I guess, um, for, for an experienced shopper, um, what, what would that number look like? How many missions would they get per month and what would their total pay across all the missions be? Okay. Okay. I see.",
      "Um, and is, is-- are there any sort of like bonuses, I guess on top of this? Got it. Okay.",
      "Um, and in terms of availability, um, when do you normally expect us to take on missions? Um, I'm just wondering if I can fit this in as a thing to do after my day job, which is-- which basically ends at five PM. Um, so yeah, I'm, I'm wondering if that would work with my schedule. Okay. I see.",
      "And, um, you know, in term, uh, in terms of like in, in certain cases where there may be like a lot more traffic than normal, um, do we get compensated for that extra time that we spend doing a particular mission? Mm. Okay. I see.",
      "Um, cool. I'm just thinking of what more questions I may have. Um, I guess, uh, the last question I had is, um, is there anything that I need to, um, a-any sort of experience that I need to have beforehand before I can like apply for this or be-- for you to consider my application? Okay. Cool. And yeah, I guess, uh, I'll apply then. Yeah. Thank you very much for answering my questions."
    ],
    "audio": "audio/recording-1cs-surgical.mp3"
  },
  {
    "id": "recording-1-cs-aggressive",
    "title": "Mystery Shopper — Parisian · audio NO commas at all (TEST)",
    "date": "2026-06-24",
    "source": "s2t-test",
    "french": [
      "Bonjour. Euh, alors je viens de voir votre annonce en ligne sur, euh, genre, le fait de devenir client mystère pour vous. Euh, donc je voulais, enfin je voulais juste vous appeler parce que j'avais deux-trois questions quand j'ai vu l'annonce, si ça vous dérange pas. Super.",
      "Euh, alors déjà, euh, je vois pas trop ce que c'est, les missions. Du coup c'est, c'est quoi exactement, une mission ? Genre, euh, je, je sais qu'on va, euh, qu'on va aller faire des courses, qu'on va aller au restaurant, tout ça. En gros on va acheter les services des autres, quoi. Euh, mais du coup après, qu'est-ce qui se passe ?",
      "D'accord. Euh, et j'imagine que ma question c'est plutôt, genre, qu'est-ce que vous allez faire de cette évaluation ? Genre, euh, vous allez la poster en ligne ? Vous euh— est-ce que, est-ce que notre nom est associé à ça quand vous le postez en ligne ? Si c'est le cas, ben c'est ça la partie que je voudrais clarifier. D'accord. Euh, et est-ce que les— enfin, est-ce que les évaluations, euh, sont postées en ligne, ou alors c'est juste pour votre, j'imagine, euh, pour, pour votre base de connaissances interne, pour connaître vos concurrents ou je sais pas quoi ? D'accord. D'accord. Je vois.",
      "Euh, et je voulais aussi en savoir plus sur la rémunération. Euh, donc vous avez dit que la paye dépend des missions. Euh, vous pourriez développer un peu ? Je vois. D'accord.",
      "Euh, et on peut espérer avoir combien de missions, genre, par mois ? Parce que, euh, je, je me demande s'il y aura une forme de régularité à l'avenir une fois qu'on aura un peu d'expérience, parce que je sais que, genre, quand on débute, ben les missions arrivent peut-être pas de manière régulière, mais je me demande si ça pourrait finir par atteindre le point où, genre, on a des missions genre régulièr— de manière régulière, du coup c'est plus prévisible. D'accord. Je vois.",
      "Et euh, j'imagine, euh, pour, pour un livreur expérimenté, euh, ça, ça représenterait quoi comme chiffre ? Combien de missions ils auraient par mois et ça ferait combien au total, la paie sur toutes les missions ? D'accord. D'accord. Je vois.",
      "Euh, et est-ce que, est-ce qu'il y a un peu des, genre des primes, j'imagine, en plus de ça ? Je vois. D'accord.",
      "Euh, et au niveau des disponibilités, euh, quand est-ce que vous attendez normalement de nous qu'on prenne des missions ? Euh, je me demande juste si je peux caser ça comme un truc à faire après mon travail, qui, qui finit en gros à dix-sept heures. Euh, du coup voilà, je, je me demande si ça collerait avec mon emploi du temps. D'accord. Je vois.",
      "Et, euh, vous savez, au niv-, euh, au niveau de dans certains cas où il y aurait genre beaucoup plus de circulation que d'habitude, euh, est-ce qu'on est dédommagé pour ce temps en plus qu'on passe sur une mission ? Hmm. D'accord. Je vois.",
      "Euh, super. Je réfléchis juste aux questions que je pourrais encore avoir. Euh, du coup, euh, la dernière question que j'avais, c'est, euh, est-ce qu'il y a quelque chose que je dois, euh, une-, une expérience que je dois avoir au préalable avant de pouvoir genre postuler, ou que-- pour que vous considériez ma candidature ? D'accord. Super. Et voilà, euh, du coup, euh, je vais postuler alors. Voilà. Merci beaucoup d'avoir répondu à mes questions."
    ],
    "english": [
      "Hi. Um, so I just saw your posting online about, um, you know, becoming a mystery shopper for you guys. Um, so I just, I just wanted to call you guys because I had a couple questions when I saw the posting, if that's okay with you. Great.",
      "Um, so first of all, um, I'm not really clear on what missions are. So what, what do you mean by missions? So, um, I, I know that, you know, we'll be, uh, we'll be going shopping, we'll be going through a restaurant, all that stuff. We'll be essentially buying other people's services. Um, but then what's next after that?",
      "Okay. Um, and I guess my question is more about like, what are you going to do with that evaluation? Like, um, are you going to post about it online? Do you like-- Is, is our name involved with that when you post it online? If that's the case, like that's the part that I want to clarify on. Okay. Um, and are the-- So are the evaluations, um, posted online or is it just for your internal, I guess, um, for, for your internal knowledge base to know about your competitors or whatever the case may be? Okay. Okay. I see.",
      "Um, and I also want to know more about the pay. Um, so you mentioned that the pay is based on missions. Um, could you elaborate on that? I see. Okay.",
      "Um, and how many missions can we expect to get, you know, like per month? Because, um, I, I'm wondering if there will be some sort of consistency in the future once we get a certain amount of experience because I know, you know, as a beginner, like the missions might not come like consistently, but I'm wondering if it could eventually reach that point where, you know, we get missions like consistent-- on a consistent basis so it's more predictable. Okay. I see.",
      "And I guess, um, for, for an experienced shopper, um, what, what would that number look like? How many missions would they get per month and what would their total pay across all the missions be? Okay. Okay. I see.",
      "Um, and is, is-- are there any sort of like bonuses, I guess on top of this? Got it. Okay.",
      "Um, and in terms of availability, um, when do you normally expect us to take on missions? Um, I'm just wondering if I can fit this in as a thing to do after my day job, which is-- which basically ends at five PM. Um, so yeah, I'm, I'm wondering if that would work with my schedule. Okay. I see.",
      "And, um, you know, in term, uh, in terms of like in, in certain cases where there may be like a lot more traffic than normal, um, do we get compensated for that extra time that we spend doing a particular mission? Mm. Okay. I see.",
      "Um, cool. I'm just thinking of what more questions I may have. Um, I guess, uh, the last question I had is, um, is there anything that I need to, um, a-any sort of experience that I need to have beforehand before I can like apply for this or be-- for you to consider my application? Okay. Cool. And yeah, I guess, uh, I'll apply then. Yeah. Thank you very much for answering my questions."
    ],
    "audio": "audio/recording-1cs-aggressive.mp3"
  },
  {
    "id": "recording-4",
    "title": "Restaurant Picnic Basket Offer Inquiry",
    "date": "2026-06-24",
    "source": "s2t",
    "french": [
      "Bonjour. Euh, du coup je viens de voir votre annonce en ligne sur votre offre spéciale de lancement. Euh, vous voyez, le fait que vous proposez, euh, des paniers à emporter ou à se faire livrer. Euh, je voulais juste demander, euh, je voulais juste vous appeler pour poser quelques questions de plus sur ce que c'est exactement que vous proposez. Cool. Euh, voilà. Donc euh, la première chose que je voulais demander, c'est, euh, qu'est-ce qu'il y a exactement dans le panier ?",
      "D'accord. Euh, et puis j'ai aussi vu dans l'annonce que vous mentionniez que, euh, il y a plein de variétés de paniers au choix. Vous pourriez me donner quelques exemples ? Genre, c'est quoi les options les plus, euh, populaires ?",
      "Okay. Euh, et niveau prix, je pars sur quoi là ? Genre, euh, ça coûte combien un panier en général ? Et c'est quoi la taille des portions d'un panier ? Genre, ça fait combien de parts un panier ?",
      "Okay. Donc ça fait, euh, vingt-cinq dollars pour un panier pour une seule part qui en gros sert... Genre, c'est en gros juste pour un repas. Ah d'accord, je vois.",
      "Okay. Euh, est-ce que vous proposez des réductions pour, j'imagine, genre les clients ré-réguliers ou pour, vous voyez, les personnes âgées ou pour les étudiants ou pour les enfants ? Une variation de prix quelconque selon ces critères ?",
      "Okay. Euh, et vous avez dit que vous pouvez aussi livrer ces paniers. Je me demandais s'il y a genre des frais de li- de livraison pour ça, ou est-ce qu'il y a une li- ou est-ce que, genre, euh, genre une limite à la distance sur laquelle vous pouvez livrer un panier ?",
      "Ça marche. Okay. Et il est situé où exactement, ce restaurant ?",
      "D'accord. Euh, c'est noté. D'accord. Et vous avez parlé d'un truc genre une offre de lancement spéciale. Euh, pardon si vous l'avez déjà dit, mais est-ce que vous pourriez, euh, me reparler de l'offre de lancement spéciale ?",
      "Ok, super. Euh, et est-ce qu'on a des genre bonus genre si on recommande des gens à votre service ?",
      "Ok, cool. Euh, je réfléchis juste à quelles autres questions j'ai envie de poser. Euh, est-ce que vous— Ou genre vous, vous avez dit qu'on— qu'il y a une possibilité de composer notre propre menu pour les paniers. Euh, jusqu'à, jusqu'à quel point c'est le cas ? Genre est-ce qu'on— est-ce qu'on peut choisir littéralement n'importe quoi, genre n'importe quel type de bouffe qu'on veut dans un panier ? Ou genre, vous voyez, on a une l— liste d'ingrédients dans laquelle choisir ou un truc comme ça ?",
      "D'accord. Euh, je vois. Et du coup, euh, je veux aussi en savoir plus sur genre ce qui vous différencie de genre... Enfin, en quoi, en quoi c'est différent de genre juste commander un repas dans un restaurant ou de la vente à emporter ? Genre qu'est-ce qui, qu'est-ce qui vous différencie de ça ?",
      "Ah, d'accord. Ok, je vois. Euh, et ça vous prend combien de temps en général pour préparer un panier ? Je me demande juste, euh, genre, euh, à quel po— combien de temps à l'avance on doit commander un panier avant genre la sortie pique-nique ou un truc comme ça.",
      "J'ai compris. D'accord. Euh, ouais, je pense que c'est toutes les questions que j'avais pour vous. Euh, merci beaucoup pour votre temps et d'avoir répondu à mes questions."
    ],
    "english": [
      "Hi. Um, so I just saw your ad online about your special launch offer. Um, you know, that you're offering, uh, baskets to take away or to be delivered. Um, I just wanted to ask, uh, I just wanted to call you guys to ask a bit more questions about what exactly it is that you're offering. Cool. Um, yeah. So I, uh, first thing I wanted to ask is, um, what exactly is included in the basket?",
      "Right. Um, and I also saw that in the ad that you mentioned that, um, there are numerous varieties of baskets to choose from. Could you give me some examples? Like, what are the most, um, popular options?",
      "Okay. Um, and in terms of cost, what am I looking at here? Like, um, how much does a basket typically cost? And how much is the portion size of a basket? Like, how many portions can a basket serve?",
      "Okay. So that's, um, twenty-five dollars for one basket for a single serving that basically serves... Like, it's basically just for one meal. Gotcha.",
      "Okay. Um, do you offer any discounts for, I guess, like re-repeat customers or for, you know, elderly citizens or for students or for children? Any sort of variations in prices based on those factors?",
      "Okay. Um, and you mentioned that you are also able to deliver these baskets. I'm wondering if there's like a de-delivery fee for that, or is there l- or is this there, like, um, like a limit to how far you can deliver a basket?",
      "Got it. Okay. And where exactly is this restaurant situated?",
      "Okay. Um, got it. Okay. And you mentioned something about a special launch offer. Um, I'm sorry if you've already mentioned this, but could you please, um, tell me about the special launch offer again?",
      "Okay, cool. Um, and do we get any like bonuses in case like we refer people to your service?",
      "Okay, cool. Um, just thinking of what more questions I have that I want to ask. Um, do you-- Or like you, you mentioned that we-- there's a possibility to put together our own menu for the baskets. Um, to what, to what extent is this the case? Like do we-- can we choose literally anything, like any type of food that we want in a basket? Or like, you know, we have a l-list of ingredients to choose from or something like that?",
      "Okay. Um, I see. And I guess, uh, I also want to know more about like what differentiates you from like... Well, how, how is this different from like just ordering a meal from a restaurant or takeout? Like what, what separates you guys from that?",
      "Oh, okay. Okay, I see. Um, and how long does it usually take for you to prepare one basket? I'm just, uh, wondering like how, um, how f- how long in advance we have to order a basket before like the picnic outing or something like that.",
      "Got it. Okay. Um, yeah, I think that's all the questions I had for you. Um, thank you very much for your time and for answering my questions."
    ],
    "audio": "audio/recording-4.mp3"
  },
  {
    "id": "recording-3",
    "title": "Calling About TV-Tester Gig",
    "date": "2026-06-24",
    "source": "s2t",
    "french": [
      "Bonjour. Euh, alors j'ai vu votre annonce en ligne sur, vous voyez, en gros le fait de devenir, euh, testeurs d'émissions de télé pour vous. Et je voulais juste appeler pour avoir plus d'informations sur, euh, ce poste, ou ce job, je sais pas, euh, si ça vous dérange pas. Parfait.",
      "Euh, alors du coup ma première question, c'est, euh, qu'est-ce que vous entendez exactement par tester ? Genre, je sais qu'on va regarder des séries, et qu'en gros on va donner notre avis, mais je me demande juste à quoi ça ressemble, un test. Genre, c'est quoi, c'est quoi concrètement ce qu'on doit rendre ? D'accord. Euh, et qu'est-ce que... Euh,",
      "du coup, comment, combien de temps il dure, le, euh, le questionnaire ou le sondage qu'on doit remplir ? Genre, ça prendrait combien de minutes pour cette partie ? Euh, d'accord.",
      "Euh, et du coup je voulais aussi en savoir plus sur, genre, ce que vous-- ce qui vient après ça. Genre, qu'est-ce que, qu'est-ce que vous faites concrètement avec nos évaluations ? Genre, vous les postez en ligne ? Et si c'est le cas, genre, est-ce que, est-ce que notre nom est associé à ça ? C'est aussi la partie que je voulais clarifier. OK, super.",
      "Euh, et je voulais juste-- je voulais aussi, euh, juste être sûr si, genre, est-ce que vous nous demandez nos vrais avis sincères ou c'est, genre, un truc où vous vous attendez à ce qu'on donne des faux témoignages, on va dire ? OK, j'ai compris. J'ai compris. D'accord. C'est bon à savoir.",
      "Euh, et je voulais aussi en savoir plus sur la rémunération. Donc, euh, vous mentionnez dans l'annonce que vous proposez des bons d'achat comme paiement. Euh, vous pourriez développer là-dessus ? Genre, ça vaut combien, un bon d'achat ? OK, je vois.",
      "Et, euh, combien de tests, euh, vous attendez de nous, disons, genre par mois ? Genre, euh, je sais que, vous voyez, en tant que débutants, on aurait sûrement pas beaucoup de tests, mais je me demande juste si à l'avenir, à un certain niveau de com— si, si une fois qu'on atteint un certain niveau d'expérience, je me demande si on peut s'attendre à commencer à recevoir des tests de manière plus régulière, plus constante, pour que le revenu de cette source soit plus prévisible. D'accord.",
      "Euh, donc pour un testeur plus expérimenté, euh, genre combien de tests, euh… je, je sais pas, euh, com— combien il toucherait au total sur l'ensemble des tests qu'il fait ? Et j'imagine, genre, ma question qui suit, c'est, genre, est-ce qu'il y a des bonus en plus de la paie de base que vous avez déjà mentionnée ? D'accord.",
      "Euh, et désolé si je l'ai dé— si je l'ai déjà demandé, mais combien de temps ça prendrait en général en moyenne pour terminer un test, même, genre, surtout un à ce niveau, euh, j'imagine, euh, plus expérimenté, ou à ce poste ? D'accord. Ok, super.",
      "Euh, qu'est-ce qu'on a d'autre ? Ah, pardon. Qu'est-ce qu'on a, euh… je réfléchis juste aux autres questions qu'il me reste. Euh, est-ce qu'il y a une pénalité si on n'arrive pas à terminer un test dans les temps, comme vous vous y attendez ? Je vois. D'accord.",
      "Euh, et est-ce qu'il y a une sorte d'expérience que vous attendez de nous au préalable avant de, genre, en quelque sorte, euh, considérer notre candidature ? Top.",
      "Euh, ouais, j'imagine, euh, que c'est à peu près toutes les questions que j'avais pour vous. Merci beaucoup pour votre temps."
    ],
    "english": [
      "Hi. Um, so I saw your ad online about, you know, essentially becoming, uh, TV show testers for you guys. And I just wanted to call to get more information about, uh, this position or this gig, I guess, um, if that's okay with you. Perfect.",
      "Um, so I guess my first question is, um, what exactly do you mean by test? Like, I know that we'll be watching TV shows, and we'll essentially be giving our opinions, but I'm just wondering what a test looks like. Like, what, what's the actual deliverable? Okay. Um, and what, what does...",
      "Um, so how, how long is the actual, um, questionnaire or survey that we have to fill out? Like, how many minutes would it take for this part? Uh, okay.",
      "Um, and I guess I also wanted to know more about, like, what you-- what comes after this. Like, what, what do you actually do with our evaluations? Like, do you post them online? And if that's the case, like, is, is our name associated with that? That's also the part that I wanted to clarify. Okay, cool.",
      "Um, and I just wanted to-- I also wanted to, um, just make sure if there's like, are you asking us for our actual genuine opinions or is it, like, something like you expect us to give fake testimonials, so to say? Okay, got it. Got it. Okay. That's good to know.",
      "Um, and I also wanted to know more about the pay. So, um, you mentioned in the ad that you're offering gift vouchers as pay. Um, could you elaborate on that? Like, how much is one gift voucher? Okay, I see.",
      "And, um, how many tests, uh, do you expect us to get, let's say, like per month? Like, um, I know that, you know, as beginners, we probably wouldn't get a lot of tests, but I'm just wondering if in the future, at a certain level of s-- if, if once we get to a certain level of experience, I'm wondering if we can expect to start getting tests on a more regular, consistent basis, so the income from the source is more predictable. Okay.",
      "Um, so for a more experienced tester, um, like how many tests, uh... I, I guess, um, how, how much total pay would they expect to get across all the tests that they do? And I guess, like, my follow-up question to that is, like, are there any bonuses on top of the base pay that you already mentioned? Okay.",
      "Um, and I'm sorry if I've alr- I've already asked this, but how long would it usually take on average for us to complete one test, even, like, particularly one where in that more experienced, um, I guess, uh, level or position? Okay. Okay, cool.",
      "Um, what else do we have? Oh, sorry. What else, uh... I'm just thinking of what other questions I may still have. Um, is there any penalty that we get if we are not able to complete a test on time that you expect us to complete? Got it. Okay.",
      "Um, and is there any sort of experience that you expect us to have beforehand before you, like, sort of, um, consider our application? Cool.",
      "Um, yeah, I guess, uh, that's pretty much all the questions that I have for you. Thank you very much for your time."
    ],
    "audio": "audio/recording-3.mp3"
  },
  {
    "id": "recording-2",
    "title": "Food Product Tester Job Inquiry",
    "date": "2026-06-24",
    "source": "s2t",
    "french": [
      "Bonjour. Euh, ouais, je voulais juste vous appeler parce que j'ai vu votre annonce à propos, enfin, en gros de devenir testeur de produits alimentaires pour vous. Euh, j'avais, j'avais juste, euh, juste quelques questions quand j'ai vu l'annonce, donc, euh, je voulais juste vous appeler si ça vous dérange pas. Cool.",
      "Euh, du coup je dirais que ma première question, c'est, euh, on teste quoi exactement et vous entendez quoi exactement par tester ? Genre, je sais que, enfin, c'est des produits alimentaires, mais quel genre de produits alimentaires et qu'est-ce que vous-- qu'est-ce que vous entendez exactement par tester ? D'accord, je vois.",
      "Euh, et juste pour éviter genre les mauvaises surprises, genre est-ce que vous nous demandez notre avis sincère ou est-ce qu'on doit un peu donner genre, euh, je sais pas, un avis inventé pour que ça colle à ce que vous, euh, voulez, que-- quel que soit le narratif que vous voulez créer ou pour, pour… Et on est rémunérés pour ça ? Est-ce, est-ce que c'est genre, est-ce que c'est ce genre de truc ou est-ce que c'est genre vous voulez vraiment connaître notre vrai avis ? D'accord, je vois.",
      "Et du coup, euh, je voulais aussi en savoir plus sur genre le, euh, le but derrière tout ça. Genre qu'est-ce-- je, je sais qu'on devra donner notre feedback, mais c'est pour quoi exactement ? Genre, est-ce que vous allez publier dessus en ligne ? Et si c'est le cas, genre, est-ce que notre nom est associé à ça ? Genre, c'est aussi la partie sur laquelle je voulais avoir des précisions. D'accord, je vois.",
      "Euh, et on peut-- Juste, juste, juste pour confirmer encore une fois, genre on peut choisir de garder notre nom genre complètement anonyme, c'est ça ? Parfait. Euh, cool.",
      "Et je voulais aussi en savoir plus sur genre la paie. Euh, parce que je le vois pas mentionné sur l'annonce, donc genre est-ce que vous pourriez m'en dire plus sur genre comment on va être rémunérés pour ce travail ? Euh, ok.",
      "Du coup, euh, j'imagine que ma première question de suivi là-dessus c'est genre, combien, euh, de sessions on peut espérer avoir par mois ? Euh, genre je sais que... D-disons, disons les choses comme ça. Euh, genre je sais qu'en tant que débutant on aurait sûrement pas genre énormément de sessions, vous voyez, mais je me, je me dema- je me demande juste genre si à l'avenir on peut arriver à u-- une fois qu'on arrive à un certain niveau d'expérience, genre si on peut espérer avoir plus de sessions ou de façon plus régulière, pour que ce soit plus prévisible. Ok.",
      "Euh, du coup genre pour, pour un, euh, testeur de produits alimentaires expérimenté, com- combien de sessions il peut espérer avoir par mois et, euh, ça donnerait quoi sa rémunération totale sur toutes les sessions qu'il a dans le mois ? Ok, ça marche. D'accord.",
      "Et est-ce qu'il y a des primes en plus de ça ? D'accord. Ok, je vois.",
      "Euh, et au niveau de, euh, genre est-ce que, est-ce que vous attendez de nous qu'on ait une sorte d'expérience au préalable avant, vous voyez, de genre considérer notre annonce, euh, pardon, considérer notre candidature ou un truc dans le genre ? Ok, super.",
      "Euh, et est-ce qu'il y a genre un certain niveau de qualité de feedback que vous attendez de nous, genre au niveau de genre la longueur que ça doit faire, à quel point ça doit être détaillé, euh, et j'imagine le niveau de langue qu'on, qu'on doit avoir pour ce feedback ? Ok, cool.",
      "Euh, j'imagine que c'est toutes les questions que j'avais pour vous. Euh, je vais y réfléchir. Je vais réfléchir à postuler. Voilà. Merci beaucoup pour votre temps."
    ],
    "english": [
      "Hi. Um, yeah, I just wanted to call you guys because I saw your posting about, you know, essentially being food product testers for you guys. Um, I, I just, uh, just had a few questions when I saw the posting, so, um, just wanted to call you if that's okay with you. Cool.",
      "Um, so I guess my first question is, um, what exactly are we testing and what exactly do you mean by testing? Like, I know that, you know, they're food products, but what kind of food products and what do you-- what exactly do you mean by testing? Okay, I see.",
      "Um, and just to prevent any sort of surprises, like are you asking us for our genuine opinion or do we have to sort of give like, uh, I don't know, a made-up opinion so it fits what-whatever you, um, want, what-whatever narrative you want to spin up or for, for... And we get compensated for that? Is, is it like, is it that kind of stuff or is it like you genuinely want to know our true opinion? Okay, I see.",
      "And I guess, um, I also wanted to know more about like the, um, the purpose behind this. Like what-- I, I know that we'll have to give our feedback, but what exactly is that for? Like, are you going to post about it online? And if that's the case, like, is our name associated with that? Like, that's also the part that I wanted to clarify on. Okay, I see.",
      "Um, and we can-- Just, just, just to confirm one more time, like we can choose to keep our name like completely anonymous, right? Perfect. Um, cool.",
      "And I also wanted to know more about like the pay. Um, so I don't see it being mentioned on the ad, so like could you talk to me more about like how we're going to be compensated for this job? Uh, okay.",
      "So, um, I guess my first follow-up question to that is like, how many, um, rounds can we expect to get per month? Uh, like I know... L-let's say, let's put it like this. Um, like I know as a beginner we probably wouldn't get like a lot of rounds, you know, but I'm, I'm won- I'm just wondering like if in the future we can get to a-- once we get to a certain level of experience, like whether we can expect to get more rounds or on a more consistent basis, so it's more predictable. Okay.",
      "Um, so like for, for an experienced, uh, food product tester, how, how many rounds can they expect to get per month and, um, what would their total pay look like across all the rounds that they get per month? Got it. Okay.",
      "And are there any bonuses on top of that? Okay. Okay, I see.",
      "Um, and in terms of, um, like do, do you expect us to have any sort of experience beforehand before, you know, you like consider our posting or, sorry, consider our application or something like that? Okay, cool.",
      "Um, and is there like a certain level of quality of feedback that you expect from us, like in terms of like how long it has to be, how detailed it has to be, um, and I guess the level of language we, we require to have for that feedback? Okay, cool.",
      "Um, I guess that's all the questions that I had for you guys. Um, I'll consider this. I'll consider applying. Yeah. Thank you very much for your time."
    ],
    "audio": "audio/recording-2.mp3"
  },
  {
    "id": "recording-1",
    "title": "Mystery Shopper Job Inquiry",
    "date": "2026-06-21",
    "source": "s2t",
    "french": [
      "Bonjour. Euh, donc je viens de voir votre annonce en ligne sur, euh, vous voyez, devenir client mystère pour vous. Euh, donc je voulais juste, je voulais juste vous appeler parce que j'avais deux-trois questions quand j'ai vu l'annonce, si ça vous dérange pas.",
      "Super. Euh, donc tout d'abord, euh, je suis pas trop au clair sur ce que c'est, les missions. Donc qu'est-ce que, qu'est-ce que vous voulez dire par missions? Genre, euh, je, je sais que, vous voyez, on va, euh, on va aller faire les courses, on va aller dans un restaurant, tout ça. On va en gros acheter les services des autres. Euh, mais après, c'est quoi la suite?",
      "D'accord. Euh, et je suppose que ma question c'est plus genre, qu'est-ce que vous allez faire avec cette évaluation? Genre, euh, est-ce que vous allez la poster en ligne? Est-ce que vous, genre-- Est-ce que, est-ce que notre nom est associé à ça quand vous le postez en ligne? Si c'est le cas, genre c'est ça la partie que je veux clarifier.",
      "D'accord. Euh, et est-ce que les-- Donc est-ce que les évaluations, euh, sont postées en ligne ou c'est juste pour votre usage interne, je suppose, euh, pour, pour votre base de connaissances interne pour vous renseigner sur vos concurrents ou peu importe.",
      "D'accord. D'accord. Je vois. Euh, et je veux aussi en savoir plus sur la paie. Euh, donc vous avez dit que la paie est basée sur les missions. Euh, vous pourriez développer là-dessus?",
      "Je vois. D'accord. Euh, et combien de missions on peut espérer avoir, vous voyez, genre par mois? Parce que, euh, je, je me demande s'il va y avoir une sorte de régularité à l'avenir une fois qu'on aura un certain niveau d'expérience parce que je sais, vous voyez, en tant que débutant, genre les missions arrivent peut-être pas de manière régulière, mais je me demande si ça pourrait finir par atteindre ce point où, vous voyez, on reçoit des missions genre régulièr-- de manière régulière donc c'est plus prévisible.",
      "Okay. Je vois. Et j'imagine, euh, pour, pour un shopper expérimenté, euh, ça, ça représenterait combien ? Combien de missions est-ce qu'il aurait par mois et ça ferait combien au total, la paie sur toutes les missions ?",
      "Okay. Okay. Je vois. Euh, et est-ce que, est-ce qu'-- est-ce qu'il y a genre des bonus, j'imagine, en plus de ça ?",
      "Okay, compris. Okay. Euh, et au niveau des disponibilités, euh, quand est-ce que vous attendez normalement qu'on prenne des missions ? Euh, je me demande juste si je peux caser ça comme un truc à faire après mon travail principal, qui se-- qui finit en gros à cinq heures de l'après-midi. Euh, du coup ouais, je me, je me demande si ça marcherait avec mon emploi du temps.",
      "Okay. Je vois. Et, euh, vous savez, en ter-, euh, en termes de genre dans, dans certains cas où il y aurait genre beaucoup plus de circulation que d'habitude, euh, est-ce qu'on est dédommagé pour ce temps en plus qu'on passe à faire une mission en particulier ?",
      "Mhm. Okay. Je vois. Euh, cool. Je réfléchis juste à quelles autres questions je pourrais avoir. Euh, j'imagine, euh, la dernière question que j'avais c'est, euh, est-ce qu'il y a quelque chose que je dois, euh, un-une quelconque expérience que je dois avoir au préalable avant de pouvoir genre postuler à ça ou que-- que vous considériez ma candidature ?",
      "Okay. Cool. Et ouais, j'imagine, euh, je vais postuler alors. Ouais. Merci beaucoup d'avoir répondu à mes questions."
    ],
    "english": [
      "Hi. Um, so I just saw your posting online about, um, you know, becoming a mystery shopper for you guys. Um, so I just, I just wanted to call you guys because I had a couple questions when I saw the posting, if that's okay with you.",
      "Great. Um, so first of all, um, I'm not really clear on what missions are. So what, what do you mean by missions? So, um, I, I know that, you know, we'll be, uh, we'll be going shopping, we'll be going through a restaurant, all that stuff. We'll be essentially buying other people's services. Um, but then what's next after that?",
      "Okay. Um, and I guess my question is more about like, what are you going to do with that evaluation? Like, um, are you going to post about it online? Do you like-- Is, is our name involved with that when you post it online? If that's the case, like that's the part that I want to clarify on.",
      "Okay. Um, and are the-- So are the evaluations, um, posted online or is it just for your internal, I guess, um, for, for your internal knowledge base to know about your competitors or whatever the case may be?",
      "Okay. Okay. I see. Um, and I also want to know more about the pay. Um, so you mentioned that the pay is based on missions. Um, could you elaborate on that?",
      "I see. Okay. Um, and how many missions can we expect to get, you know, like per month? Because, um, I, I'm wondering if there will be some sort of consistency in the future once we get a certain amount of experience because I know, you know, as a beginner, like the missions might not come like consistently, but I'm wondering if it could eventually reach that point where, you know, we get missions like consistent-- on a consistent basis so it's more predictable.",
      "Okay. I see. And I guess, um, for, for an experienced shopper, um, what, what would that number look like? How many missions would they get per month and what would their total pay across all the missions be?",
      "Okay. Okay. I see. Um, and is, is-- are there any sort of like bonuses, I guess on top of this?",
      "Got it. Okay. Um, and in terms of availability, um, when do you normally expect us to take on missions? Um, I'm just wondering if I can fit this in as a thing to do after my day job, which is-- which basically ends at five PM. Um, so yeah, I'm, I'm wondering if that would work with my schedule.",
      "Okay. I see. And, um, you know, in term, uh, in terms of like in, in certain cases where there may be like a lot more traffic than normal, um, do we get compensated for that extra time that we spend doing a particular mission?",
      "Mm. Okay. I see. Um, cool. I'm just thinking of what more questions I may have. Um, I guess, uh, the last question I had is, um, is there anything that I need to, um, a-any sort of experience that I need to have beforehand before I can like apply for this or be-- for you to consider my application?",
      "Okay. Cool. And yeah, I guess, uh, I'll apply then. Yeah. Thank you very much for answering my questions."
    ],
    "audio": "audio/recording-1.mp3?v=2"
  }
];
